menu:
    Blog: /
    Archive: /archives/
    GitHub: https://github.com/YanWQ-monad
    Rss: /atom.xml

favicon: /images/favicon.png
logo: /images/favicon.png

# Comment
# e.g disqus: seansun
disqus:
duoshuo:

# Analytics
# google-analytics:
gtm: GTM-PP344KH

# Copyright Infomation
startyear: 2017
